export const StaticText = {
    selectTransferTypeLabel : 'Select Transfer Types',
    selectOrderTypeLabel : 'Select Order Types',
    selectSupplier : 'Select Supplier',
    orderType : 'Order Type',
    routeId : 'Route Id',
    customerId : 'Customer Id',
    routeCode : 'Route Code',
    supplier : 'Supplier',
    stop: 'Stop#',
    transferType : 'Transfer Type',
    processDate : 'Process Date',
    refDoc : 'Ref Doc#',
    deliveryDate : 'Delivery Date',
    comments : 'Comments',
    headerUpdate : 'Header Update',
    orderIdPlaceHolder : 'Order Id',
    itemNumber : 'Item Number',
    from : 'from',
    to: 'to',
    date : 'Date',
    division : 'Division',
    orderStatusLabel : 'Select Order Status',
    selectChangeReason : 'Select Change Reason',
    orderStatus : 'Order Status',
    searchQuery : 'Please enter search criteria to fetch the results!',
    dateType : 'Select Date Type',
    details : 'Details',
    logistics : 'Logistics',
    ok :'OK',
    emailId : 'Email Id',
    userId: 'User Id',
    editHeader: 'Header Details',
    nodataFound: 'No any data found!',
    editSubmitText: 'Submit',
    editCancelText: 'Cancel',
    headerUpDateLabel : 'Bulk Update'
 };