export const StaticText = {
    selectTransferTypeLabel : 'Select Transfer Types',
    selectOrderTypeLabel : 'Select Order Types',
    selectSupplier : 'Select Supplier',
    orderType : 'Order Type',
    routeId : 'Route Id',
    customerId : 'Customer Id',
    routeCode : 'Route Code',
    supplier : 'Supplier',
    stop: 'Stop',
    transferType : 'Transfer Type',
    processDate : 'Process Date',
    refDoc : 'Ref Doc',
    deliveryDate : 'Delivery Date',
    comments : 'Comments',
    headerUpdate : 'Header Update',
    orderIdPlaceHolder : 'Order Id',
    itemNumber : 'Item Number',
    from : 'from',
    to: 'to',
    date : 'Date',
    division : 'Division',
    orderStatusLabel : 'Select Order Status',
    orderStatus : 'Order Status',
    searchQuery : 'Please enter search criteria to fetch the results!',
    dateType : 'Select Date Type'
 };